# nginx proxy address - http://172.17.0.1:60121

name: openproject
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: openproject/openproject:latest
    container_name: openproject-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      OPENPROJECT_HOST__NAME: ${BASE_HOST_NAME:-$HOSTNAME}
      OPENPROJECT_SECRET_KEY_BASE: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      OPENPROJECT_EMAIL__DELIVERY__METHOD: smtp
      OPENPROJECT_SMTP__ADDRESS: ${EMAIL_SERVER_HOST:-172.17.0.1}
      OPENPROJECT_SMTP__PORT: ${EMAIL_SERVER_PORT:-587}
      OPENPROJECT_SMTP__DOMAIN: ${BASE_DOMAIN_NAME:-example.com}
      OPENPROJECT_SMTP__AUTHENTICATION: login
      OPENPROJECT_SMTP__ENABLE__STARTTLS__AUTO: "true"
      OPENPROJECT_SMTP__USER__NAME: ${EMAIL_SERVER_LOGIN_NAME:-}
      OPENPROJECT_SMTP__PASSWORD: ${EMAIL_SERVER_LOGIN_PASS:-}
      OPENPROJECT_MAIL__FROM: ${EMAIL_SERVER_MAIL_FROM:-openproject@example.com}
      CONTAINER_NAME: openproject-app
    ports:
      - '172.17.0.1:60121:80'
    volumes:
      - './volumes/data/openproject/assets:/var/openproject/assets:z'
      - './volumes/data/openproject/pgdata:/var/openproject/pgdata:z'
    networks:
      - openproject
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://openproject-app:80'
      - 'cloudflare.hostname=openproject.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.openproject-app.entrypoints=http'
      - 'traefik.http.routers.openproject-app-secure.tls=true'
      - 'traefik.http.routers.openproject-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.openproject-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.openproject-app.middlewares=openproject-app-https-redirect'
      - 'traefik.http.routers.openproject-app-secure.entrypoints=https'
      - 'traefik.http.routers.openproject-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.openproject-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.openproject-app-secure.service=openproject-app'
      - 'traefik.http.services.openproject-app.loadbalancer.server.port=80'

networks:
  openproject:
    name: openproject
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
